# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 654c533c38c60a94821b90afe2a4ac1a17216a16022eb0480f88c6cee6babe111ad12cbc4f6aa300b88e9662ef0283151a34977509f83e31dc96c94022ae4fb6

test:
  secret_key_base: 9d2950b34c416d3a4f00be05e276cde8ddd61cc7020953ef0b332b065deeb5974f24dcf0514fa7ee923a7782bd48810a2c409c04fffbcb7601e2c48eab6f0844

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
